name: Build Extension

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-extension:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install zip
      run: sudo apt-get install -y zip

    # Tag processing (runs on all tag pushes)
    - name: get tag params
      if: startsWith(github.ref, 'refs/tags/')
      uses: olegtarasov/get-tag@v2.1.4
      id: tagName
      with:
        tagRegex: '^(?<type>[a-zA-Z0-9]+)_(?<version>\d+\.\d+)$'

    # Version determination
    - name: Determine version number
      id: version
      run: |
        if [ "${{ startsWith(github.ref, 'refs/tags/') }}" = "true" ]; then
          if [[ "${{ github.ref }}" == *"feature_"* ]] || [[ "${{ github.ref }}" == *"dev_"* ]]; then
            echo "0" > major_version.txt
            echo "${{ github.run_number }}" > minor_version.txt
            echo "major=0" >> $GITHUB_ENV
            echo "minor=${{ github.run_number }}" >> $GITHUB_ENV
            echo "build_type=feature" >> $GITHUB_ENV
            echo "tag_type=custom" >> $GITHUB_ENV
          else
            echo "1" > major_version.txt
            echo "${{ github.run_number }}" > minor_version.txt
            echo "major=1" >> $GITHUB_ENV
            echo "minor=${{ github.run_number }}" >> $GITHUB_ENV
            echo "build_type=release" >> $GITHUB_ENV
            echo "ta
